// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wfdyirgkpqeamxsdbjbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZHlpcmdrcHFlYW14c2RiamJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjI5MDQsImV4cCI6MjA3MDU5ODkwNH0.EcCopSQvTbj4RSP_cPQn45N48q_NoTQxosQxLsvopxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});